name: gpu-python-webinar
channels:
- conda-forge
- rapidsai
- nvidia
- nodefaults
dependencies:
- python 3.10.*
- numpy >=1.26.4,<2
- pandas >=1.5.3,<2
- matplotlib-base >=3.9,<4
- numba >=0.60.0,<0.61
- cuda-version >=11.2,<12.0
- cudatoolkit *
- rapidsai::cubinlinker
- ptxcompiler *
- rapidsai::cudf 23.*
- rapidsai::rmm 23.*
- rapidsai::librmm 23.*
- cupy >=11.6.0,<12
- pycuda >=2024.1,<2025
- nvidia::cuda-nvcc >=11,<12
- pip
- pip:
  - --index-url https://pypi.org/simple
  - --extra-index-url https://pypi.nvidia.com/
  - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
  - --find-links https://storage.googleapis.com/jax-releases/jax_releases.html
  - jax[cuda11-local]==0.4.24
  - jaxlib
  - jupyterlab>=4.2.5, <5
  - jupyterlab-myst>=2.4.2, <3
  - jupyterlab-git>=0.50.1, <0.51
  - jupyterlab-lsp>=5.1.0, <6
  - python-lsp-server[all]>=1.12.0, <2
  - pytest>=8.3.3, <9
