[project]
authors = ["Ashwin V. Mohanan <ashwin.mohanan@enccs.se>"]
channels = ["conda-forge", "rapidsai", "nvidia"]
description = "Add a short description here"
name = "2024-oct-24-python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numba = ">=0.60.0,<0.61"
python = "3.12.*"
cuda-nvcc = ">=12,<13"
cuda-nvrtc = ">=12,<13"
cuda-version = "12.*"
cudf = {version="24.10.*", channel="rapidsai"}
# rmm = {channel="rapidsai"}
# librmm = {channel="rapidsai"}
matplotlib-base = ">=3.9.2,<4"
cuda-python = ">=12.6.0,<13"
cupy = ">=13.3.0,<14"
pycuda = ">=2024.1,<2025"
# rapids = {version="24.10.*", channel="rapidsai"}
# dask-cuda = {version="24.10.*", channel="rapidsai"}
# pylibcugraph = {channel="rapidsai"}
# libcugraph = {channel="rapidsai"}
# rapids-xgboost = {channel="rapidsai"}
# libxgboost = {channel="rapidsai"}

# rapids = "24.10.*"
# cupy = {version=">=12", channel="conda-forge"}
# ucx = {channel="conda-forge"}
# datashader = {channel="conda-forge"}

[pypi-options]
extra-index-urls = ["https://pypi.nvidia.com"]

[pypi-dependencies]
polars = { version = ">=1.8.2, <2", extras = ["gpu"] }
jupyterlab = ">=4.2.5, <5"

